name: walle
description: Android development tools
version: 0.1.0

publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  app_store_server_sdk: ^1.2.8
  args: ^2.1.0
  googleapis: ^12.0.0
  googleapis_auth: ^1.3.1
  in_date_range: ^1.0.0+1
  in_date_utils: ^1.0.1+1
  list_ext: ^1.0.4
  meta: ^1.7.0
  path: ^1.8.0
  string_ext: ^0.2.0
  xml: ^6.0.1

dev_dependencies:
  innim_lint: ^0.4.0
